### ISSUE TITLE
Adding labels to LKE node pools

### ISSUE THREAD

**Issue by erir910** [linode/linodego#196]
I know that has nothing to do with lindoego directly but I hope you forward this to whoever is in charge on this issue, LKE currently does not support adding kubernetes labels to node pools. This very little feature is basically one of the very main reasons of having separate node pools in the first place. AFAIK almost all managed k8s solutions support adding kubernetes labels to node pools/groups using the cloud vendor APIs.

**Comment by g1bl3t** [comment]
Hey @erir910, your message made it to the LKE team - thanks for the feedback! We've heard this request before and it's something we plan to implement. I don't have an ETA on that quite yet, but it's on our roadmap. I'm going to close this issue since it's not directly related to linodego. If you have any other suggestions or feedback for the LKE team you can open a Support ticket or send an email to feedback@linode.com. This is the most direct way to get in touch with us.
